# permissions to do viewer codeservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codeserver-viewer-role
rules:
- apiGroups:
  - cs.tommylike.com
  resources:
  - codeservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cs.tommylike.com
  resources:
  - codeservers/status
  verbs:
  - get
