apiVersion: cs.opensourceways.com/v1alpha1
kind: CodeServer
metadata:
  name: resources-1-container-x86-1
  namespace: default
spec:
  args:
    - zsh
  connectProbe: /active-time
  egressBandwidth: 1M
  envs:
    - name: GOTTY_ONLY_ENABLE_BACKEND_WS_SERVER
      value: "false"
    - name: GOTTY_CREDENTIAL
      value: 428d6bde63f0cf9e:61773a4bd99b249af3953bbddf0e7b1a
    - name: SHELL_USER
      value: zhangjianjun_code
    - name: GOTTY_MAX_CONNECTION
      value: "10"
    - name: COMMUNITY_EMAIL
      value: contact@openeuler.io
    - name: GOTTY_WS_ORIGIN
      value: .*
    - name: GOTTY_PERMIT_WRITE
      value: "true"
  image: opensourceway/openeuler-20.03-lts-sp1-base:latest@sha256:4e94a5b8e3636df00eebb042e43c1941dc46c9395cce54f96e414bee0eab3c57
  inactiveAfterSeconds: 0
  ingressBandwidth: 10M
  privileged: false
  readinessProbe:
    httpGet:
      path: /active-time
      port: 80
    initialDelaySeconds: 6
    periodSeconds: 3
    timeoutSeconds: 3
  recycleAfterSeconds: 12000
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  runtime: gotty
  storageName: emptyDir
  storageSize: 500Mi
  subdomain: resfc6cb5c95f229a26554ff06a5884c
  workspaceLocation: /workspace
