apiVersion: cs.opensourceways.com/v1alpha1
kind: CodeServer
metadata:
  name: codeserver-sample
spec:
  runtime: gotty
  url: codeserversample
  image: "opensourceway/openeuler-20.03-lts-sp1-base:latest"
  volumeSize: "10Gi"
  storageClassName: "csi-disk"
  pvcAnnotations:
    everest.io/disk-volume-type: SSD
  inactiveAfterSeconds: 60
  recycleAfterSeconds: 60
  workspaceLocation: "/workspace"
  envs:
    - name: GOTTY_ONLY_ENABLE_BACKEND_WS_SERVER
      value: "false"
    - name: GOTTY_CREDENTIAL
      value: name:password
    - name: SHELL_USER
      value: tommylikehu
    - name: COMMUNITY_EMAIL
      value: contact@openeuler.io
    - name: GOTTY_WS_ORIGIN
      value: ".*"
    - name: GOTTY_PERMIT_WRITE
      value: "true"
  args:
    - zsh
  connectProbe: "/active-time"
  privileged: false
  resources:
    requests:
      cpu: "1"

