apiVersion: cs.opensourceways.com/v1alpha1
kind: CodeServer
metadata:
  name: codeserver-lxd-sample
spec:
  runtime: lxd
  subdomain: codeserverzhangjianjun
  image: "opensourceway/playground-lxc-launcher:sha-f6b536b"
  storageSize: "10Gi"
  storageName: "default"
  ingressBandwidth: "10M"
  egressBandwidth: "10M"
  inactiveAfterSeconds: 0
  recycleAfterSeconds: 12000
  readinessProbe:
    httpGet:
      path: "/active-time"
      # connection port will be updated according to the http or https schema
      port: 8080
    initialDelaySeconds: 6
    periodSeconds: 3
    timeoutSeconds: 3
  workspaceLocation: "/workspace"
  envs:
    # env for gotty
    - name: GOTTY_ONLY_ENABLE_BACKEND_WS_SERVER
      value: "false"
    - name: GOTTY_CREDENTIAL
      value: name:password
    - name: COMMUNITY_USER
      value: zhangjianjun
    - name: GOTTY_MAX_CONNECTION
      value: "10"
    - name: COMMUNITY_EMAIL
      value: contact@openeuler.io
    - name: GOTTY_WS_ORIGIN
      value: ".*"
    - name: GOTTY_PERMIT_WRITE
      value: "true"
    # env for lxd launcher
    - name: LAUNCHER_ADDITIONAL_CONFIG #keep
      value: raw.lxc=lxc.apparmor.profile=unconfined,security.nesting=true,security.privileged=true
    - name: LAUNCHER_INSTANCE_PROFILES #keep
      value: default
    - name: LAUNCHER_IMAGE_ALIAS #keep
      value: openeuler-gotty
    # env for terminal
    - name: TERM
      value: xterm
  connectProbe: "/active-time"
  privileged: false
  resources:
    requests:
      cpu: "1"
      memory: "500Mi"
